### ISSUE TITLE
JQuery not loading on Chrome

### ISSUE THREAD

**Issue by equationcrunchor** [AndrewVSutherland/psetpartners#217]
On Chrome for Mac OS, the page fails to load aside from the headers and footers.  The console prints this message:

```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js' with computed SHA-256 integrity 'kZMXypKF3if9/5v2tP9UHBvS/535tSyH7vjszruyCso='. The resource has been blocked.
```

Site works fine with Safari.

**Comment by AndrewVSutherland** [comment]
Thanks for the bug report.  I'm surprised by this because researchseminars uses the same jquery link and we haven't had any problems reported there, and I just ran a test using https://app.crossbrowsertesting.com/ running Chrome 84 and Mac/OS 10.14 and it seems fine.  Can I ask if you get the same error when you visit https://researchseminars.org ?

And can you tell me the version of Mac OS and Chrome?

**Comment by equationcrunchor** [comment]
Chrome is 64-bit 85.0.4183.83.  Mac is 10.15.6 Catalina.  

I see the same error in the console on researchseminars.org, although the page appears to load fine.

**Comment by AndrewVSutherland** [comment]
Can I ask you to try https://psetpartners-test.mit.edu/ and tell me if it loads for you?

**Comment by equationcrunchor** [comment]
Seems to load perfectly fine.  No error in console

**Comment by AndrewVSutherland** [comment]
OK, I just pushed this to the live site, let me know if it works for you now.

**Comment by equationcrunchor** [comment]
Works fine.  Thank you!

**Comment by AndrewVSutherland** [comment]
No problem, thanks for letting me know!
